package apperror

import (
	"github.com/pkg/errors"
)

var (
	ErrDatabaseConnection    = errors.New("1002")
	ErrUnauthorizedAccess    = errors.New("1003")
	ErrInvalidHTTPHeader     = errors.New("1004")
	ErrInvalidPayloadFormat  = errors.New("1005")
	ErrRedisConnection       = errors.New("1006")
	ErrDataNotFound          = errors.New("1007")
	ErrEndpointDeprecated    = errors.New("1008")
	ErrBadRequestPayload     = errors.New("1009")
	ErrSignatureExpired      = errors.New("1010")
	ErrDecodingFailure       = errors.New("1011")
	ErrUnmarshallingFailure  = errors.New("1012")
	ErrUserInfoNotFound      = errors.New("1013")
	ErrInvalidUUID           = errors.New("1014")
	ErrInternalServerError   = errors.New("1015")
	ErrStatusConflict        = errors.New("1016")
	ErrUnprocessableEntity   = errors.New("1017")
	ErrTimeoutOccurred       = errors.New("1018")
	ErrServiceUnavailable    = errors.New("1019")
	ErrPermissionDenied      = errors.New("1020")
	ErrInvalidRequest        = errors.New("1021")
	ErrResourceLimitExceed   = errors.New("1022")
	ErrAuthenticationFailed  = errors.New("1023")
	ErrRateLimitExceeded     = errors.New("1024")
	ErrFeatureNotImplemented = errors.New("1025")
	ErrMethodNotAllowed      = errors.New("1026")
	ErrRequestTimeout        = errors.New("1027")
	ErrConflictDetected      = errors.New("1028")
	ErrInvalidCredentials    = errors.New("1029")
	ErrPaymentRequired       = errors.New("1030")
	ErrForbiddenAccess       = errors.New("1031")
	ErrResourceGone          = errors.New("1032")
	ErrPreconditionFailed    = errors.New("1033")
	ErrTooManyRequests       = errors.New("1034")
	ErrLegalRestriction      = errors.New("1035")
	ErrInvalidCacheDuration  = errors.New("1036")
	ErrPasswordHashingFailed = errors.New("1037")
	ErrTokenGeneration       = errors.New("1038")
	ErrInvalidToken          = errors.New("1039")
	ErrInvalidTokenClaims    = errors.New("1040")
	ErrTokenExpired          = errors.New("1041")

	ErrEmailRequired        = errors.New("1101")
	ErrInvalidEmail         = errors.New("1102")
	ErrPasswordRequired     = errors.New("1103")
	ErrPasswordMinMaxLength = errors.New("1104")
	ErrInvalidPassword      = errors.New("1105")

	ErrEmailOrPhoneNumberRequired = errors.New("1106")
	ErrInvalidEmailOrPhoneNumber  = errors.New("1107")
	ErrOtpTypeRequired            = errors.New("1108")
	ErrInvalidOtpType             = errors.New("1109")
	ErrLoginTokenRequired         = errors.New("1110")

	ErrOrganizationNameRequired     = errors.New("1111")
	ErrOrganizationNameMinMaxLength = errors.New("1112")
	ErrPhoneNumberRequired          = errors.New("1113")
	ErrPhoneNumberMinMaxLength      = errors.New("1114")
	ErrAddressRequired              = errors.New("1115")
	ErrAddressMinMaxLength          = errors.New("1116")
	ErrSubdomainNameRequired        = errors.New("1117")
	ErrSubdomainNameMinMaxLength    = errors.New("1118")
	ErrDomainNameRequired           = errors.New("1119")
	ErrDomainNameMinMaxLength       = errors.New("1120")
	ErrActivePeriodIDRequired       = errors.New("1121")
	ErrFullNameRequired             = errors.New("1122")
	ErrFullNameMinMaxLength         = errors.New("1123")
	ErrEmailAlreadyExists           = errors.New("1124")
	ErrPhoneNumberAlreadyExists     = errors.New("1125")
	ErrSubdomainNameAlreadyExists   = errors.New("1126")
	ErrRequestOtpRequired           = errors.New("1127")
	ErrRoleIDRequired               = errors.New("1128")
	ErrPasswordMismatch             = errors.New("1129")
	ErrEmailTemplateParse           = errors.New("1130")
	ErrEmailTemplateExecution       = errors.New("1131")
	ErrEmailSendFailure             = errors.New("1132")
	ErrInvalidPhotoBase64           = errors.New("1133")
	ErrSocialMediaTokenRequired     = errors.New("1134")
	ErrCampaignIDsRequired          = errors.New("1135")
	ErrUserIDsRequired              = errors.New("1136")
	ErrServiceNameRequired          = errors.New("1137")
	ErrInvalidServiceName           = errors.New("1138")
	ErrCampaignSummaryUnavailable   = errors.New("1139")
	ErrCampaignDetailsUnavailable   = errors.New("1140")
	ErrInvalidPhoneNumber           = errors.New("1141")
	ErrFundingTargetMinMaxLength    = errors.New("1142")
	ErrInvalidCampaignExpiredDate   = errors.New("1143")
	ErrInvalidCampaignImage         = errors.New("1144")
	ErrShortDescriptionMinMaxLength = errors.New("1145")
	ErrCampaignNotEligibleForUpdate = errors.New("1146")
	ErrCampaignIDRequired           = errors.New("1147")
	ErrTitleRequired                = errors.New("1148")
	ErrTitleTooLong                 = errors.New("1149")
	ErrContentRequired              = errors.New("1150")

	ErrProgramNameRequired              = errors.New("1151")
	ErrProgramNameMinLength             = errors.New("1152")
	ErrProgramNameMaxLength             = errors.New("1153")
	ErrInitialInvestmentRequired        = errors.New("1154")
	ErrInitialInvestmentGreaterThanZero = errors.New("1155")
	ErrStartDateRequired                = errors.New("1156")
	ErrStartDateInvalidFormat           = errors.New("1157")
	ErrEndDateRequired                  = errors.New("1158")
	ErrEndDateInvalidFormat             = errors.New("1159")
	ErrStartDateAfterEndDate            = errors.New("1160")
	ErrEvaluationFrequencyRequired      = errors.New("1161")
	ErrInvalidEvaluationFrequency       = errors.New("1162")
	ErrOrgIDRequired                    = errors.New("1163")

	ErrStakeholderNameRequired          = errors.New("1164")
	ErrStakeholderNameMinLength         = errors.New("1165")
	ErrStakeholderNameMaxLength         = errors.New("1166")
	ErrInvestmentTypeRequired           = errors.New("1167")
	ErrInvalidInvestmentType            = errors.New("1168")
	ErrStakeholderCountCannotBeNegative = errors.New("1169")
	ErrProgramIDRequired                = errors.New("1170")

	ErrOutcomeNameRequired              = errors.New("1171")
	ErrOutcomeNameMinLength             = errors.New("1172")
	ErrOutcomeNameMaxLength             = errors.New("1173")
	ErrModalValueRequired               = errors.New("1174")
	ErrModalValueMustBePositive         = errors.New("1175")
	ErrKPIIndicatorMustBeValid          = errors.New("1176")
	ErrAttributePercentageOutOfRange    = errors.New("1177")
	ErrDisplacementPercentageOutOfRange = errors.New("1178")
	ErrDeadweightPercentageOutOfRange   = errors.New("1179")
	ErrDropOffPercentageOutOfRange      = errors.New("1180")
	ErrStakeholderIDRequired            = errors.New("1181")
	ErrInvalidEvaluationDate            = errors.New("1182")
	ErrDocumentUploadFailed             = errors.New("1183")

	ErrDocumentTypeRequired                        = errors.New("1184")
	ErrInvalidDocumentType                         = errors.New("1185")
	ErrFileBase64Required                          = errors.New("1186")
	ErrInvalidFileBase64                           = errors.New("1187")
	ErrFileNameRequired                            = errors.New("1188")
	ErrFileNameTooShort                            = errors.New("1189")
	ErrFileNameTooLong                             = errors.New("1190")
	ErrOutcomeIDRequired                           = errors.New("1191")
	ErrEvaluationDateRequired                      = errors.New("1192")
	ErrEvaluationDateInvalidFormat                 = errors.New("1193")
	ErrEvaluationStatusRequired                    = errors.New("1194")
	ErrInvalidEvaluationStatus                     = errors.New("1195")
	ErrCurrentFinancialValueRequired               = errors.New("1196")
	ErrCurrentFinancialValueGreaterThanOrEqualZero = errors.New("1197")
	ErrEvaluationIDRequired                        = errors.New("1198")
	ErrProgramStatusRequired                       = errors.New("1199")
	ErrInvalidProgramStatus                        = errors.New("1200")

	ErrSendOtpFromKbWong       = errors.New("1201")
	ErrResendOtpFromKbWong     = errors.New("1202")
	ErrValidateOtpFromKbWong   = errors.New("1203")
	ErrLoginSosmedFromKbWong   = errors.New("1204")
	ErrRefreshTokenFromKbWong  = errors.New("1205")
	ErrGetUserInfoFromKbWong   = errors.New("1206")
	ErrKbCampaignInDraftStatus = errors.New("1207")

	ErrStakeholderReachedGreaterThanOrEqualZero = errors.New("1208")
	ErrStakeholderReachedExceedTheLimits        = errors.New("1209")

	ErrRetrieveDataFromKbKampanye = errors.New("1210")

	ErrSanguDisburseInquiryAccountInProgress       = errors.New("1301")
	ErrSanguDisburseInquiryAccountInvalidAccNumber = errors.New("1302")
	ErrSanguDisburseInquiryAccountSuspected        = errors.New("1303")
	ErrSanguSomethingWentWrong                     = errors.New("1304")
	ErrBankCodeRequired                            = errors.New("1305")
	ErrBankNameRequired                            = errors.New("1306")
	ErrBankAccountNumberRequired                   = errors.New("1307")
	ErrInvalidDisbursementID                       = errors.New("1308")
	ErrDisbursementReceiptStatusInvalid            = errors.New("1309")
	ErrDisbursementReceiptFileNameRequired         = errors.New("1310")
	ErrDisbursementReceiptDescriptionRequired      = errors.New("1311")
	ErrDisbursementAmountRequired                  = errors.New("1312")
	ErrDisbursementDescriptionRequired             = errors.New("1313")
	ErrDisbursementParameterUseReceiptRequired     = errors.New("1314")
	ErrDisbursementParameterUseReceiptInvalid      = errors.New("1315")
	ErrDisbursementOTPCodeRequired                 = errors.New("1316")

	ErrCampaignDraftShortURLRequired = errors.New("1401")

	ErrNGOFundingProgramTitleRequired              = errors.New("1501")
	ErrNGOFundingProgramTitleMinMaxLength          = errors.New("1502")
	ErrNGOFundingProgramDescriptionRequired        = errors.New("1503")
	ErrNGOFundingProgramCoverImageRequired         = errors.New("1504")
	ErrNGOFundingProgramSubmissionDeadlineRequired = errors.New("1505")
	ErrNGOFundingProgramSubmissionDeadlineInvalid  = errors.New("1506")
	ErrNGOFundingProgramPeriodRequired             = errors.New("1507")
	ErrNGOFundingProgramImplementationCostGT0      = errors.New("1508")
)
